<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>cmacc</string>
    <key>scopeName</key>
    <string>scope.cmacc</string>
    <key>fileTypes</key>
    <array>
      <string>cmacc</string>
      <string>CMACC</string>
    </array>
    <key>uuid</key>
    <string>7df5a01c-4d9e-4ca5-b38a-7305e49d6e71</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>storage.type.cmacc</string>
        <key>match</key>
        <string>\$\s+(\w+)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>storage.modifier.cmacc</string>
        <key>match</key>
        <string>\w*(\=\>)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.cmacc</string>
        <key>match</key>
        <string>(\{\{\S*\S\}\})</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.cmacc</string>
        <key>match</key>
        <string>\w*(\".*\")</string>
      </dict>
    </array>
  </dict>
</plist>